language: python

python:
  - 3.6.8
  - 3.7
  - 3.8

services:
  - docker

before_script:
  - docker run --name mongodb -d mongo
  - entrypoint="$(echo "$(cat deploy/entrypoint)")"
  - echo "${entrypoint/gunicorn -w $\{WORKERS_NUM\} -k uvicorn.workers.UvicornWorker  -b 0.0.0.0:80 quizer.asgi:application/cd \/usr\/share\/python3\/quizer && \/usr\/share\/python3\/venv\/bin\/python runtests.py}" > deploy/entrypoint

script:
  - MONGO_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' mongodb)
  - docker build -t quizer .
  - docker run -e MONGO_HOST=$MONGO_IP quizer
