language: python

python:
  - 3.6.8
  - 3.7
  - 3.8

services:
  - docker

before_script:
  - docker run --name mongodb -d mongo
  - entrypoint="$(echo "$(cat deploy/entrypoint)")"
  - echo "${entrypoint/uvicorn quizer.asgi:application --host 0.0.0.0 --port 80/python manage.py test main}" > deploy/entrypoint

script:
  - MONGO_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' mongodb)
  - docker build -t quizer .
  - docker run -e MONGO_HOST=$MONGO_IP quizer
