language: python

python:
  - "3.6.8"

services:
  - docker

before_script:
  - pip install docker-compose
  - entrypoint="$(echo "$(cat deploy/entrypoint)")"
  - echo "${entrypoint/runserver 0.0.0.0:80/test main}" > deploy/entrypoint

script:
  - docker build -t quizer .
  - docker run quizer
