language: python

python:
  - 3.6.8
  - 3.7
  - 3.8

services:
  - docker

before_script:
  - pip install docker-compose
  - entrypoint="$(echo "$(cat deploy/entrypoint)")"
  - echo "${entrypoint/runserver 0.0.0.0:80/test main}" > deploy/entrypoint

script:
  - docker-compose run web sh -c "echo Passed all tests!"
