version: '3'

services:
  quizer:
    image: quizer:latest
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    networks:
      - net
  mongo:
    image: mongo:latest
    networks:
      - net

networks:
  net:

