name: Docker

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6.8, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Configure app
        run: |
          pip install docker-compose
          entrypoint="$(echo "$(cat deploy/entrypoint)")"
          echo "${entrypoint/runserver 0.0.0.0:80/test main}" > deploy/entrypoint
      - name: Build docker container & running tests
        run: |
          docker-compose run web sh -c "echo Passed all tests!"
