name: Docker

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6.8, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run Mongo
        run: |
          docker run --name mongodb -d mongo
      - name: Configure app
        run: |
          entrypoint="$(echo "$(cat deploy/entrypoint)")"
          echo "${entrypoint/runserver 0.0.0.0:80/test main}" > deploy/entrypoint
      - name: Build docker container & running tests
        run: |
          MONGO_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' mongodb)
          docker build -t quizer .
          docker -e MONGO_HOST=$MONGO_IP run quizer
